### ISSUE TITLE
entities\cell.go error

### ISSUE THREAD

**Issue by jdude104** [joeygibson/life#1]
Running life.go yields the following error:
"# github.com/joeygibson/life/entities
D:\go\src\pkg\github.com\joeygibson\life\entities\cell.go:32: function ends with
out a return statement"

**Comment by joeygibson** [comment]
What version of Go are you using, and how did you try to run it?

**Comment by jdude104** [comment]
go version: 1.0.2
I ran it by moving the required packages into the go directory so that it would match how its referred to in the code, then went to life.go's directory and ran "go run life.go"

**Comment by joeygibson** [comment]
That's an ancient version of Go. Assuming you have installed Termbox, and your $GOPATH is setup correctly, you should be able to follow the directions on the main page, without having to move anything around. I just tried it myself with a new clone of the repo, using Go dev version from August, and it worked fine.
